DATASET_NAME=event_element
all:
	python run_${DATASET_NAME}.py \
		--do_experiment \

train:
	python run_${DATASET_NAME}.py \
		--do_train \

eval:
	python run_${DATASET_NAME}.py \
		--do_eval \

predict:
	python run_${DATASET_NAME}.py \
		--do_predict \

eda:
	python run_${DATASET_NAME}.py \
		--do_eda \

submit:
	python run_${DATASET_NAME}.py \
		--do_submit \

